(() => {
  const storageKey = "desvio-language";
  const requested = new URLSearchParams(location.search).get("lang");
  const stored = (() => { try { return localStorage.getItem(storageKey); } catch { return null; } })();
  const language = requested === "en" || (!requested && stored === "en") ? "en" : "pt";
  const locale = language === "en" ? "en-GB" : "pt-PT";
  document.documentElement.lang = locale;

  const exact = new Map(Object.entries({
    "Saltar para a agenda":"Skip to the listings","Saltar para o evento":"Skip to the event","Saltar para os eventos":"Skip to the events","Desvio — Menos procura. Mais música. Voltar ao início":"Desvio — Less searching. More music. Back to the start","Ver site em português":"View site in Portuguese",
    "Agenda de concertos e festivais em Portugal | Desvio":"Concerts and festivals in Portugal | Desvio","Encontra concertos, festivais e música ao vivo em Portugal. Pesquisa por cidade, data, género e bilhetes na agenda Desvio.":"Find concerts, festivals and live music in Portugal. Search by city, date, genre and tickets with Desvio.","Encontra concertos, festivais e música ao vivo em Portugal — por cidade, data, género e bilhetes.":"Find concerts, festivals and live music in Portugal — by city, date, genre and tickets.",
    "Música em Portugal":"Music in Portugal","Completa a agenda":"Complete the listings","A tua agenda de música":"Your live music guide","A agenda de música em Portugal":"Portugal’s live music guide",
    "Menos procura.":"Less searching.","Mais música.":"More music.","Menos procura. Mais música.":"Less searching. More music.",
    "Todos os géneros. Todas as cidades. Um desvio que vale a pena.":"Every genre. Every city. A detour worth taking.",
    "Concertos, festivais e underground. Todo o país, numa só agenda.":"Concerts, festivals and underground music. The whole country in one guide.","Procurar na agenda":"Search the listings","Pesquisar":"Search","Próximo evento em destaque":"Featured upcoming event","A confirmar o próximo evento…":"Confirming the next event…","Ainda estamos a confirmar o próximo evento.":"We are still confirming the next event.","Explorar a agenda":"Explore the listings","Ver evento":"View event",
    "A seguir":"Up next","Próximos eventos.":"Upcoming events.","Os cinco primeiros eventos depois de hoje.":"The next five events after today.","Ver agenda completa":"View the full listings",
    "Perto de ti":"Near you","A acontecer na tua área.":"Happening near you.","Navegar eventos próximos":"Browse nearby events","Eventos anteriores":"Previous events","Mais eventos":"More events","Cinco próximos eventos por ordem cronológica":"Five upcoming events in chronological order",
    "Encontra algo teu.":"Find your thing.","Atalhos rápidos da agenda":"Quick listing shortcuts","Hoje":"Today","Este fim de semana":"This weekend","Próximos 7 dias":"Next 7 days","Entrada livre":"Free admission",
    "Artista, sala ou cidade":"Artist, venue or city","Procurar artista, sala ou cidade":"Search artist, venue or city","Filtros":"Filters","Fechar filtros":"Close filters",
    "Quando":"When","Todas as datas":"All dates","Próximo mês":"Next month","Entrada":"Admission","Qualquer entrada":"Any admission","Com bilhetes":"Tickets available","Por confirmar":"To be confirmed","Esgotado":"Sold out","Disponível":"Available","Cancelado":"Cancelled",
    "Preço":"Price","Qualquer preço":"Any price","Até 10 €":"Up to €10","Mais de 50 €":"Over €50","Preço por confirmar":"Price to be confirmed",
    "Género":"Genre","Todos os géneros":"All genres","Formato":"Format","Todos os formatos":"All formats","Onde":"Where","Ver na minha região":"Show my area",
    "Distrito":"District","Todos os distritos":"All districts","Área":"Area","Todas as áreas":"All areas","Concelho / cidade":"Municipality / city","Todos os concelhos":"All municipalities",
    "Limpar seleção":"Clear selection","Destaques":"Highlights","Festivais":"Festivals","Underground":"Underground","Esgotados":"Sold out",
    "Eventos encontrados":"Events found","Modo de visualização":"View mode","Lista":"List","Calendário":"Calendar","Data":"Date","Evento":"Event","Bilhetes":"Tickets","Detalhes":"Details",
    "Não encontrámos eventos com esta combinação.":"We found no events matching this combination.","Limpar filtros":"Clear filters","Mês anterior":"Previous month","Mês seguinte":"Next month","Paginação de eventos":"Event pagination","Anterior":"Previous","Seguinte":"Next","← Anterior":"← Previous","Seguinte →":"Next →",
    "Mais informação":"More information","Como verificamos os eventos":"How we verify events","Fontes que acompanhamos":"Sources we monitor",
    "Incluímos toda a música pública: festivais, concertos, bares, Fado, DJ sets, recitais, ópera e musicais. Revistas, blogs, Reddit e Instagram ajudam-nos a encontrar sinais. Um evento só surge como disponível quando a respetiva venda foi confirmada; os restantes ficam como “por confirmar”. A percentagem de lotação só aparece quando é divulgada pelo promotor.":"We include public music in every form: festivals, concerts, bars, Fado, DJ sets, recitals, opera and musicals. Magazines, blogs, Reddit and Instagram help us spot leads. An event is only marked as available once ticket sales are confirmed; all others remain ‘to be confirmed’. Capacity percentages only appear when announced by the promoter.",
    "Desvio — Menos procura. Mais música.":"Desvio — Less searching. More music.","Explorar e informação":"Explore and information","Grátis":"Free","Termos":"Terms","Privacidade":"Privacy","És promotor ou geres uma sala?":"Are you a promoter or venue manager?","Junta a tua agenda ao Desvio.":"Add your listings to Desvio.",
    "Cartaz ampliado":"Enlarged poster","Fechar cartaz":"Close poster","Cartaz oficial ampliado":"Enlarged official poster","Contribuir para a agenda":"Contribute to the listings","Sugerir um evento.":"Suggest an event.",
    "Partilha um link oficial. A sugestão será sempre revista antes de aparecer na agenda.":"Share an official link. Every suggestion is reviewed before it appears in the listings.",
    "Sugerir um evento":"Suggest an event","Um concerto, festival ou noite que deve entrar na agenda.":"A concert, festival or night that should be listed.","Adicionar página de promotora":"Add a promoter page","Uma promotora, sala ou projeto com agenda pública.":"A promoter, venue or project with public listings.",
    "O teu nome":"Your name","Email":"Email","para respondermos":"so we can reply","Artista, festival ou nome do evento":"Artist, festival or event name","Cidade / concelho":"City / municipality","Cidade / área":"City / area","Géneros":"Genres","Página da agenda":"Listings page","Link oficial":"Official link","Cartaz oficial":"Official poster",
    "Obrigatório: deixa o link do cartaz ou envia a imagem encontrada numa fonte oficial.":"Required: add the poster link or upload the image found on an official source.","Link do cartaz":"Poster link","Enviar imagem":"Upload image","JPG, PNG ou WebP · otimizada automaticamente para até 2 MB":"JPG, PNG or WebP · automatically optimised to 2 MB or less",
    "O que devemos adicionar?":"What should we add?","Cartaz, bilheteira, horário, artistas, entrada livre ou outra informação relevante.":"Poster, ticket link, schedule, artists, free admission or other relevant information.","Li a":"I have read the","Política de Privacidade":"Privacy Policy","e compreendo que estes dados serão usados apenas para analisar este pedido.":"and understand that this data will only be used to review this request.","Enviar para revisão":"Send for review",
    "Desvio — voltar à agenda":"Desvio — back to the listings","Voltar à Agenda":"Back to the listings","A abrir evento…":"Opening event…","Agenda pública de música em Portugal.":"Portugal’s public live-music listings.","Corrigir evento":"Correct event",
    "Programação":"Programme","Dias do festival":"Festival days","Horário a confirmar":"Time to be confirmed","Bilhetes por confirmar":"Tickets to be confirmed","Percurso até ao local":"Directions to the venue","Percurso":"Directions","Fonte oficial":"Official source","Fonte":"Source","Adicionar ao Calendário":"Add to calendar",
    "Pelo caminho":"Along the way","Também pode interessar.":"You may also like.","Confirma sempre horários e disponibilidade na fonte oficial.":"Always confirm times and availability with the official source.","Cartaz oficial ainda não publicado.":"Official poster not published yet.","Estamos a acompanhar a fonte do evento.":"We are monitoring the event’s official source.",
    "Partilhar evento":"Share event","Partilhar":"Share","Leva este concerto contigo.":"Take this concert with you.","Escolhe a aplicação no menu de partilha do teu telemóvel.":"Choose an app from your phone’s share menu.","Link copiado.":"Link copied.",
    "Evento não encontrado":"Event not found","Este desvio já não está na agenda.":"This detour is no longer in the listings.","Voltar à agenda":"Back to the listings",
    "Agenda completa ↗":"Full listings ↗","Percurso":"Breadcrumb","Agenda":"Listings","Agenda confirmada · Portugal":"Verified listings · Portugal","Continuar a descobrir":"Keep exploring","Segue outro desvio.":"Take another detour.","Ainda não há eventos confirmados para esta seleção.":"There are no confirmed events for this selection yet.",
    "Ver este fim de semana":"See this weekend","Atualiza a página e talvez apareça outro membro da banda.":"Refresh the page and another band member may appear.","404 · O evento não está aqui, mas a música continua.":"404 · The event is gone, but the music plays on.","Explorar a agenda":"Explore the listings",
    "404 · Sem sinal":"404 · No signal","Puxaram-lhe a ficha.":"They pulled the plug.","Este evento ficou sem corrente.":"This event ran out of power.","Voltar ao alinhamento":"Back to the setlist",
    "404 · Fora da faixa":"404 · Off track","O disco saltou.":"The record skipped.","Este evento saiu da faixa.":"This event dropped off the track.","Voltar à agenda":"Back to the listings",
    "404 · Desvio na estrada":"404 · Tour detour","A tour perdeu-se.":"The tour got lost.","Este evento fez um desvio a mais.":"This event took one detour too many.","Traçar nova rota":"Plot a new route",
    "404 · Depois do encore":"404 · After the encore","O beat foi ao bar.":"The beat went to the bar.","E levou este evento com ele.":"And took this event with it.","Ver quem toca a seguir":"See who plays next",
    "404 · Corda partida":"404 · Broken string","A corda deu o berro.":"The string snapped.","Este evento saiu do tom.":"This event went out of tune.","Afinar nova procura":"Tune a new search",
    "Amplificador mascote com o cabo desligado":"Amplifier mascot with an unplugged cable","Disco de vinil mascote à procura do beat":"Vinyl record mascot looking for the beat","Carrinha de tour mascote num desvio":"Tour van mascot taking a detour","Bateria mascote num palco vazio":"Drum kit mascot on an empty stage","Guitarra mascote com uma corda partida":"Guitar mascot with a broken string",
    "Informação legal":"Legal information","Termos de utilização.":"Terms of use.","Política de Privacidade.":"Privacy Policy.","Política de Cookies.":"Cookie Policy.","← Voltar à agenda":"← Back to the listings","Última atualização: 2 de setembro de 2026":"Last updated: 2 September 2026","Última atualização: 21 de setembro de 2026":"Last updated: 21 September 2026",
    "Informação da agenda":"Listings information","Links e serviços de terceiros":"Third-party links and services","Cartazes, imagens e marcas":"Posters, images and trademarks","Sugestões e correções":"Suggestions and corrections","Pesquisa assistida por IA":"AI-assisted research","Uso aceitável e disponibilidade":"Acceptable use and availability","Alterações":"Changes","Contacto":"Contact",
    "O Desvio — O teu radar de eventos é uma agenda editorial de música pública em Portugal, gerida por Fábio Rafael. Ao utilizar este site, aceitas estes termos.":"Desvio — your event radar — is an editorial guide to public live music in Portugal, managed by Fábio Rafael. By using this website, you accept these terms.",
    "Procuramos indicar informação atualizada e ligar às fontes oficiais, mas programas, horários, preços, lotação, acessibilidades, cartazes e condições de entrada podem mudar. Confirma sempre no site do promotor, sala ou bilheteira antes de comprar ou viajar.":"We aim to provide current information and link to official sources, but programmes, times, prices, capacity, accessibility, posters and entry conditions may change. Always check the promoter, venue or ticketing website before buying or travelling.",
    "O Desvio não vende bilhetes, não representa organizadores nem garante a disponibilidade de entradas. As compras e condições são tratadas diretamente pela organização ou bilheteira indicada.":"Desvio does not sell tickets, represent organisers or guarantee availability. Purchases and terms are handled directly by the named organiser or ticketing provider.",
    "Os links externos são disponibilizados para conveniência. Não controlamos os respetivos conteúdos, disponibilidade, condições de venda, cookies ou políticas de privacidade. A relação com esses serviços é regida pelos respetivos termos.":"External links are provided for convenience. We do not control their content, availability, sales terms, cookies or privacy policies. Your relationship with those services is governed by their own terms.",
    "Quando disponível, apresentamos material promocional identificado como oficial e mantemos ligação para a respetiva fonte. As marcas, imagens e conteúdos pertencem aos seus titulares. Para pedir uma correção, atribuição ou remoção, escreve-nos ou usa o formulário de correção disponível na ficha do evento.":"Where available, we display promotional material identified as official and link to its source. Trademarks, images and content belong to their respective owners. To request a correction, credit or removal, contact us or use the correction form on the event page.",
    "As contribuições são analisadas antes de qualquer publicação. Só deves enviar informação, links ou imagens que possas partilhar. Ao enviares material, concedes ao Desvio uma licença não exclusiva, gratuita e limitada a rever o pedido e, se for aceite, usar esse material na respetiva ficha de evento. Não envies dados pessoais de terceiros, conteúdos ilícitos, ofensivos ou que infrinjam direitos de outras pessoas. Podemos não publicar, corrigir ou remover uma sugestão sem confirmação suficiente.":"Contributions are reviewed before publication. Only submit information, links or images you are allowed to share. By submitting material, you grant Desvio a non-exclusive, royalty-free licence limited to reviewing the request and, if accepted, using that material on the relevant event page. Do not submit third-party personal data or unlawful, offensive or rights-infringing content. We may decline, correct or remove a suggestion without sufficient confirmation.",
    "Ferramentas de inteligência artificial podem apoiar a pesquisa, organização e moderação de imagens. A decisão de publicar, alterar ou retirar uma entrada é editorial e humana. A informação continua a dever ser confirmada na fonte oficial antes de comprares bilhetes ou fazeres uma deslocação.":"Artificial-intelligence tools may support research, organisation and image moderation. Decisions to publish, change or remove an entry remain editorial and human. Information must still be confirmed with the official source before buying tickets or travelling.",
    "Não é permitido tentar interferir com o funcionamento do site, automatizar recolhas que prejudiquem o serviço, contornar medidas anti-spam ou usar o site para enviar mensagens abusivas. Podemos alterar, suspender ou atualizar funcionalidades para proteger o serviço ou o melhorar.":"You may not interfere with the website, automate collection in ways that harm the service, bypass anti-spam measures or use the website to send abusive messages. We may change, suspend or update features to protect or improve the service.",
    "Podemos atualizar estes termos quando o serviço ou a lei o exigirem. A data no início desta página indica a versão em vigor.":"We may update these terms when the service or the law requires it. The date at the top of this page identifies the current version.",
    "Para comunicar uma incorreção, pedir remoção de conteúdo ou exercer direitos sobre dados pessoais, escreve para":"To report an error, request content removal or exercise personal-data rights, write to","ou usa o formulário da agenda.":"or use the listings form.",
    "Responsável e contacto":"Controller and contact","Dados que podemos tratar":"Data we may process","Finalidades e base legal":"Purposes and legal basis","Se não forneceres os dados":"If you do not provide the data","Destinatários e tecnologias":"Recipients and technologies","Fontes públicas e transferências":"Public sources and transfers","Conservação":"Retention","Os teus direitos":"Your rights",
    "O responsável pelo tratamento dos dados é Fábio Rafael, responsável pelo projeto Desvio — O teu radar de eventos. Para questões de privacidade, contacto ou exercício de direitos:":"The data controller is Fábio Rafael, who runs the Desvio project. For privacy questions, contact or the exercise of rights:",
    "Ao navegar, a infraestrutura pode processar dados técnicos necessários ao pedido, como endereço IP, identificadores de segurança, navegador, data e hora. Quando envias uma sugestão, correção ou pedido de uma promotora, tratamos os dados do formulário: nome, email, informação do evento, cidade, links, mensagem e, se a enviares, a imagem do cartaz. O Desvio não guarda o endereço IP em texto na sua base de dados; usa apenas uma impressão criptográfica temporária para limitar abuso.":"When you browse, the infrastructure may process technical data needed to fulfil the request, such as IP address, security identifiers, browser, date and time. When you submit a suggestion, correction or promoter request, we process the form data: name, email, event information, city, links, message and, if supplied, the poster image. Desvio does not store the IP address as plain text in its database; it only uses a temporary cryptographic fingerprint to limit abuse.",
    "Tratamos estes dados para receber e rever o teu pedido, verificar fontes, gerir a agenda, responder por email, proteger formulários e defender o serviço contra fraude ou abuso. A base legal é o interesse legítimo em manter uma agenda editorial fiável e segura e em responder ao pedido que escolheste enviar. A caixa no formulário confirma que leste esta política; não é usada para te enviar marketing. Não vendemos dados nem criamos perfis publicitários.":"We process this data to receive and review your request, verify sources, manage the listings, reply by email, protect forms and defend the service against fraud or abuse. The legal basis is our legitimate interest in maintaining a reliable, secure editorial guide and responding to the request you chose to send. The form checkbox confirms that you read this policy; it is not used to send marketing. We do not sell data or create advertising profiles.",
    "Os campos obrigatórios são necessários para analisar a sugestão e, quando aplicável, responder-te. Se não os forneceres, poderemos não conseguir processar ou verificar o pedido.":"Required fields are necessary to review the suggestion and, where applicable, reply to you. Without them, we may be unable to process or verify the request.",
    "O acesso é limitado ao responsável editorial e a pessoas autorizadas a gerir o Desvio. Podemos recorrer a categorias de prestadores de alojamento, armazenamento, segurança e prevenção de abuso, métricas agregadas, envio de email e processamento de imagens. Usamos Cloudflare Web Analytics e Cloudflare Zaraz para métricas agregadas e sem cookies sobre páginas vistas e utilização das funções da agenda. Estes prestadores tratam apenas os dados necessários para prestar o respetivo serviço. Se enviares uma imagem, uma ferramenta de IA pode classificá-la para detetar conteúdo impróprio; essa classificação não publica nem rejeita uma sugestão de forma definitiva sem revisão humana.":"Access is limited to the editor and people authorised to manage Desvio. We may use providers for hosting, storage, security and abuse prevention, aggregate metrics, email delivery and image processing. We use Cloudflare Web Analytics and Cloudflare Zaraz for aggregate, cookieless metrics on page views and use of listing features. These providers process only the data needed to deliver their service. If you upload an image, an AI tool may classify it to detect inappropriate content; that classification never publishes or definitively rejects a suggestion without human review.",
    "A informação dos eventos é recolhida de fontes públicas, como promotores, salas, municípios e bilheteiras. Alguns prestadores técnicos podem tratar dados fora do Espaço Económico Europeu; quando aplicável, recorremos aos mecanismos de transferência previstos na legislação aplicável.":"Event information is collected from public sources such as promoters, venues, municipalities and ticketing providers. Some technical providers may process data outside the European Economic Area; where applicable, we use the transfer mechanisms provided by law.",
    "Os registos técnicos anti-abuso do formulário são eliminados automaticamente após uma janela curta. Os identificadores técnicos com hash usados para limitar tentativas de início de sessão são eliminados após, no máximo, 24 horas. Pedidos sem decisão são apagados após 90 dias. Pedidos publicados, recusados ou fechados são conservados até 12 meses após a decisão e são depois eliminados, salvo se forem necessários para cumprir uma obrigação legal ou tratar uma reclamação. Os acessos de administração desativados são eliminados após 12 meses.":"Technical anti-abuse form records are automatically deleted after a short period. Hashed technical identifiers used to limit sign-in attempts are deleted within 24 hours. Undecided requests are deleted after 90 days. Published, rejected or closed requests are kept for up to 12 months after the decision and then deleted, unless needed to meet a legal obligation or handle a complaint. Disabled administrator access records are deleted after 12 months.",
    "Podes pedir acesso, correção, apagamento, limitação ou oposição ao tratamento e, quando aplicável, portabilidade. Podes também apresentar reclamação à Comissão Nacional de Proteção de Dados. Para exercer estes direitos, escreve para":"You may request access, correction, deletion, restriction or objection to processing and, where applicable, portability. You may also complain to Portugal’s National Data Protection Commission. To exercise these rights, write to","Procuraremos responder no prazo legal aplicável.":"We will aim to respond within the applicable legal deadline.",
    "A nossa escolha":"Our approach","Métricas sem cookies":"Cookieless metrics","Formulários e segurança":"Forms and security","Sites de terceiros":"Third-party websites","Porque não há um banner":"Why there is no banner","Como controlar cookies":"How to control cookies",
    "O Desvio não utiliza cookies, armazenamento local ou identificadores persistentes para publicidade, remarketing, perfis, redes sociais ou medição individual de visitantes. O painel privado usa apenas um cookie de sessão estritamente necessário, HTTP-only e de duração limitada, para manter o acesso autenticado do administrador.":"Desvio does not use cookies, local storage or persistent identifiers for advertising, remarketing, profiling, social networks or individual visitor measurement. The private dashboard uses only a strictly necessary, HTTP-only, limited-duration session cookie to keep the administrator signed in.",
    "O Desvio usa armazenamento local apenas para memorizar a preferência entre português e inglês. Não utiliza cookies, armazenamento local ou identificadores persistentes para publicidade, remarketing, perfis, redes sociais ou medição individual de visitantes. O painel privado usa apenas um cookie de sessão estritamente necessário, HTTP-only e de duração limitada, para manter o acesso autenticado do administrador.":"Desvio uses local storage only to remember the choice between Portuguese and English. It does not use cookies, local storage or persistent identifiers for advertising, remarketing, profiling, social networks or individual visitor measurement. The private dashboard uses only a strictly necessary, HTTP-only, limited-duration session cookie to keep the administrator signed in.",
    "Usamos Cloudflare Web Analytics e eventos agregados do Cloudflare Zaraz, sem cookies ou identificadores persistentes, para perceber páginas vistas e interações como pesquisas, filtros, abertura de eventos, cliques em bilhetes, partilhas e submissões. Estas métricas não servem para identificar pessoas nem para seguir a navegação entre sites.":"We use Cloudflare Web Analytics and aggregate Cloudflare Zaraz events, without cookies or persistent identifiers, to understand page views and interactions such as searches, filters, event opens, ticket clicks, shares and submissions. These metrics do not identify people or track browsing across websites.",
    "Quando abres ou envias um formulário, é ativada uma verificação técnica anti-spam. Esta tecnologia pode tratar informação técnica do dispositivo e usar mecanismos estritamente necessários para distinguir pedidos legítimos de abuso. Não é usada para publicidade. O Desvio não guarda rascunhos de formulários no teu dispositivo.":"When you open or submit a form, a technical anti-spam check is activated. It may process technical device information and use strictly necessary mechanisms to distinguish legitimate requests from abuse. It is not used for advertising. Desvio does not store form drafts on your device.",
    "Os links para promotores, salas, bilheteiras ou redes sociais abrem sites independentes. Esses sites têm as suas próprias políticas de cookies e privacidade.":"Links to promoters, venues, ticketing providers or social networks open independent websites. Those websites have their own cookie and privacy policies.",
    "Atualmente não ativamos tecnologias não essenciais que exijam consentimento. Se adicionarmos publicidade, pixels, vídeos incorporados ou métricas com cookies, mostraremos antes uma escolha clara e equivalente para aceitar ou recusar e atualizaremos esta política.":"We currently do not enable non-essential technologies that require consent. If we add advertising, pixels, embedded videos or cookie-based metrics, we will first provide a clear, equivalent choice to accept or refuse and update this policy.",
    "Podes remover ou bloquear cookies nas definições do teu browser. Isto pode afetar a verificação anti-spam e outras funcionalidades técnicas, mas não deve impedir a consulta normal da agenda.":"You can remove or block cookies in your browser settings. This may affect anti-spam checks and other technical features, but should not prevent normal use of the listings.",
    "Não divulgado":"Not disclosed","Não aplicável":"Not applicable","Consultar":"See organiser","Consultar organização":"Check with organiser","Consultar programa":"See programme","Consultar horários":"See times","Consultar sessões":"See sessions","Consultar bilheteira":"See ticketing","Bilhetes online":"Online tickets","Bilhetes a confirmar":"Tickets to be confirmed","Evento terminado":"Event ended","Terminado":"Ended","Concerto":"Concert","Festival":"Festival","Recital":"Recital","Ópera":"Opera","Musical":"Musical","Festa popular":"Public festival","Concerto em bar":"Bar concert","Concerto local":"Local concert","Concerto imersivo":"Immersive concert","Cine-concerto":"Film concert","Dança e música":"Dance and music","Outro":"Other","Eletrónica":"Electronic","Alternativo":"Alternative","Clássica":"Classical","Música Portuguesa":"Portuguese music","Música Brasileira":"Brazilian music","Música Popular":"Popular music","Música de Câmara":"Chamber music","Teatro musical":"Musical theatre","Canção de autor":"Singer-songwriter","Banda sonora":"Soundtrack","Arte urbana":"Urban art","Antiga":"Early music","Fusão":"Fusion","Orquestral":"Orchestral","Contemporânea":"Contemporary","Família":"Family","Coral":"Choral","Câmara":"Chamber music","Público geral":"General audiences","Públicos jovens e famílias":"Young audiences and families","A confirmar":"To be confirmed","Adiado":"Postponed","Local a confirmar":"Venue to be confirmed","Fonte oficial confirmada pelo Desvio":"Official source verified by Desvio","Grande Lisboa":"Greater Lisbon","Grande Porto":"Greater Porto",
    "Termos — Desvio":"Terms — Desvio","Privacidade — Desvio":"Privacy — Desvio","Cookies — Desvio":"Cookies — Desvio","Termos de utilização do Desvio — O teu radar de eventos.":"Desvio terms of use — your live-music guide.","Política de Privacidade do Desvio — O teu radar de eventos.":"Desvio Privacy Policy — your live-music guide.","Política de Cookies do Desvio — O teu radar de eventos.":"Desvio Cookie Policy — your live-music guide.","Desvio — O teu radar de eventos":"Desvio — your live-music guide","O teu radar de eventos":"Your live-music guide",
    "Informação errada?":"Incorrect information?","Localização não disponível neste browser.":"Location is not available in this browser.","A localização só funciona numa ligação segura.":"Location only works over a secure connection.","A localizar a tua área…":"Finding your area…","Autoriza a localização no browser para ver eventos perto de ti.":"Allow location access in your browser to see events near you.","A localização demorou demasiado. Tenta novamente.":"Location took too long. Try again.","Não foi possível determinar a tua localização. Tenta novamente.":"We could not determine your location. Try again.","Ainda não há eventos com cartaz oficial perto de ti.":"There are no events with an official poster near you yet.",
    "Corrigir esta informação.":"Correct this information.","Adicionar uma página.":"Add a page.","Nome da promotora, sala ou projeto":"Promoter, venue or project name","Ex.: Nome da promotora ou sala":"E.g. promoter or venue name","Site oficial":"Official website","O que está errado ou desatualizado?":"What is incorrect or out of date?","Conta-nos brevemente o que programas":"Tell us briefly what you programme","Ajuda-nos a encontrar a tua agenda. A página será sempre confirmada por uma pessoa antes de entrar nas fontes do Desvio.":"Help us find your listings. A person will always verify the page before it is added to Desvio’s sources.","Preenche todos os dados e inclui uma fonte oficial. A sugestão será sempre revista antes de aparecer na agenda.":"Complete every field and include an official source. The suggestion will always be reviewed before appearing in the listings.",
    "Ao fechar, os dados ainda não enviados serão perdidos. Queres continuar?":"Closing now will discard unsent data. Do you want to continue?","O cartaz deve ser JPG, PNG ou WebP.":"The poster must be JPG, PNG or WebP.","Escolhe um cartaz com menos de 15 MB antes da otimização.":"Choose a poster under 15 MB before optimisation.","Não foi possível reduzir este cartaz para 2 MB. Tenta uma imagem mais pequena.":"We could not reduce this poster to 2 MB. Try a smaller image.","Inclui o link do cartaz ou envia uma imagem oficial.":"Include the poster link or upload an official image.","A otimizar o cartaz…":"Optimising poster…","A enviar…":"Sending…","Recebido para revisão. Se deixaste um email, usamos esse contacto apenas para responder ao pedido.":"Received for review. If you provided an email address, we will use it only to reply to the request.","Enviado ✓":"Sent ✓","Não foi possível enviar agora.":"Unable to send right now.","Não foi possível enviar agora. Tenta novamente mais tarde.":"Unable to send right now. Try again later.","Tentar novamente":"Try again","Não foi possível preparar o calendário.":"We could not prepare the calendar."
  }));

  const categoryTranslations = new Map(Object.entries({
    "Alternativo":"Alternative","Antiga":"Early music","Arte":"Art","Arte urbana":"Urban art","Axé":"Axé","Banda sonora":"Soundtrack","Barroco":"Baroque","Câmara":"Chamber music","Canção de autor":"Singer-songwriter","Cine-concerto":"Film concert","Clássica":"Classical","Clássicos":"Classics","Contemporânea":"Contemporary","Coral":"Choral","Eletrónica":"Electronic","Emergente":"Emerging","Família":"Family","Folclore":"Folk traditions","Fusão":"Fusion","Guitarra":"Guitar","Improvisada":"Improvised","Infantil":"Children’s music","Meditação":"Meditation","Metal progressivo":"Progressive metal","Música Africana":"African music","Música Antiga":"Early music","Música Cabo-verdiana":"Cape Verdean music","Natal":"Christmas","Orquestral":"Orchestral","Popular":"Popular","Progressivo":"Progressive","Psicadélico":"Psychedelic","Rock ucraniano":"Ukrainian rock","Sinfónica":"Symphonic","Tributo":"Tribute","Fado regular":"Regular Fado","Night club":"Nightclub"
  }));
  for (const [source, target] of categoryTranslations) exact.set(source, target);

  const interfaceTranslations = new Map(Object.entries({
    "Abrir evento":"Open event","Fechar":"Close","Ainda estamos a confirmar os próximos eventos.":"We are still confirming the next events.","Bilheteira a confirmar":"Ticketing to be confirmed","Não foi possível otimizar o cartaz.":"We could not optimise the poster.","Vários horários":"Various times","Horários e distribuição por dia ainda não publicados":"Times and daily schedule not yet published","Horários e distribuição por dia a anunciar":"Times and daily schedule to be announced","Passe e bilhetes diários; entrada limitada à lotação":"Pass and day tickets; admission subject to capacity","Entrada e bilheteira por confirmar":"Admission and ticketing to be confirmed",
    "Agenda de concertos, festivais e música ao vivo em Portugal.":"Live music, concert and festival listings in Portugal.","Selecionar preços de bilhete":"Select ticket prices","Selecionar géneros":"Select genres","Filtros de localização":"Location filters","Selecionar áreas":"Select areas","Destaques rápidos":"Quick highlights","Calendário de eventos":"Event calendar","Ex.: eletrónica, hip-hop, rock":"E.g. electronic, hip-hop, rock",
    "Seg":"Mon","Ter":"Tue","Qua":"Wed","Qui":"Thu","Sex":"Fri","Sáb":"Sat","Dom":"Sun",
    "Descoberta nacional":"National discovery","Promotores e bilheteiras":"Promoters and ticketing","Salas e agendas locais":"Venues and local listings","Revistas, blogs e comunidade":"Magazines, blogs and community",
    "308 agendas locais":"308 local listings","Agenda Lisboa":"Lisbon listings","Agenda Porto":"Porto listings","Agenda de concertos":"Concert listings","Agenda nacional":"National listings","Agenda por distrito":"Listings by district","Concertos e festivais":"Concerts and festivals","Eventos de música":"Music events","Concertos por artista":"Concerts by artist","Festas e concertos":"Festivals and concerts","Faro — festival municipal":"Faro — municipal festival","Sintra — agenda municipal":"Sintra — municipal listings","Amadora — concertos gratuitos":"Amadora — free concerts","Loures — cultura municipal":"Loures — municipal culture","Seixal — festas populares":"Seixal — public festivals","Lisboa — agenda oficial":"Lisbon — official listings","Leiria — agenda cultural municipal":"Leiria — municipal cultural listings","Paredes — agenda set/dez 2026":"Paredes — Sep–Dec 2026 listings","Póvoa de Varzim — bilheteira":"Póvoa de Varzim — ticketing","Vila Nova de Famalicão — bilheteira":"Vila Nova de Famalicão — ticketing",
    "Promotor":"Promoter","Promotor underground":"Underground promoter","Bilheteira":"Ticketing","Bilheteira de festivais":"Festival ticketing","Bilheteira de promotores":"Promoter ticketing","Bilheteira hardcore":"Hardcore ticketing","Bilheteira internacional":"International ticketing","Clubes e eletrónica":"Clubs and electronic music","Concertos":"Concerts","Eventos locais":"Local events","Noites e clubes":"Nights and clubs",
    "Concertos locais e bares":"Local concerts and bars","Ópera e música clássica":"Opera and classical music","Festas e palcos locais":"Festivals and local stages","Musa e salas pequenas":"Musa and small venues","Lisboa / eletrónica":"Lisbon / electronic music","Lisboa / independente":"Lisbon / independent music","Lisboa / club e concertos":"Lisbon / club and concerts","Lisboa / clássica e jazz":"Lisbon / classical and jazz","Lisboa / concertos":"Lisbon / concerts","Lisboa / doom metal":"Lisbon / doom metal","Porto / eletrónica":"Porto / electronic music","Porto / independente":"Porto / independent music","Porto / underground":"Porto / underground","Coimbra / jazz":"Coimbra / jazz","Braga / experimental":"Braga / experimental","Faro / rock e metal":"Faro / rock and metal","Música portuguesa":"Portuguese music","Comunitária":"Community","Metal, punk e pesado":"Metal, punk and heavy music","Hip-Hop e eletrónica":"Hip-hop and electronic music","Música e anúncios":"Music and announcements","Cultura e eventos":"Culture and events","Lisboa e Porto":"Lisbon and Porto"
  }));
  for (const [source, target] of interfaceTranslations) exact.set(source, target);

  const eventTitleExact = new Map(Object.entries({
    "Concerto no Bar do Rio Gondoriz":"Concert at Bar do Rio Gondoriz","Música na Esplanada":"Music on the Terrace","Festas de São Miguel":"São Miguel Festival","Cantar Juntos pelo Mundo":"Singing Together Around the World","Sinfonia n.º 5 de Beethoven":"Beethoven’s Symphony No. 5","Boca Canta Edu — Boca Livre + Edu Lobo":"Boca Sings Edu — Boca Livre + Edu Lobo","Trio Fantasma de Beethoven":"Beethoven’s Ghost Trio","Carmen de Bizet":"Bizet’s Carmen","Sul — Há Fado no Cais":"South — Fado at the Quay","Marco Rodrigues canta Carlos do Carmo":"Marco Rodrigues Sings Carlos do Carmo","Cancioneiro de Elvas — Sete Lágrimas":"Elvas Songbook — Sete Lágrimas","O Bolero de Ravel":"Ravel’s Boléro","Galáxia Vivaldi":"Vivaldi Galaxy","Concerto de Natal — Missa em Si menor de Bach":"Christmas Concert — Bach’s Mass in B minor","Clube do Choro Porto convida Cristóvão Bastos + Ilana Volcov":"Clube do Choro Porto Presents Cristóvão Bastos + Ilana Volcov","Berlioz em Itália":"Berlioz in Italy","Noite Branca — Ópera":"White Night — Opera","Clássicos de Natal 2026":"Christmas Classics 2026","Fado & Jazz: Uma Só Alma — Vânia Rodrigues e Gabriel Fialho":"Fado & Jazz: One Soul — Vânia Rodrigues and Gabriel Fialho","A Música de Mário Pacheco":"The Music of Mário Pacheco","A Voz do Rock & Convidadas":"The Voice of Rock & Guests","Lágrimas no Mar — Arnaldo Antunes e Vítor Araújo":"Tears in the Sea — Arnaldo Antunes and Vítor Araújo","A Flauta Mágica — Opera 2001":"The Magic Flute — Opera 2001","Kizomba na Rua":"Kizomba in the Street","Possível":"Possible","Patrimónios de Peso":"Weighty Heritage","Festival Jovens Músicos 2026":"Young Musicians Festival 2026","Festival Colombo 2026":"Columbus Festival 2026",
    "Bonds Festival — 3.ª edição":"Bonds Festival — 3rd Edition","Candlelight — O melhor de Adele":"Candlelight — The Best of Adele","Ciclo Mendelssohn — Integral das Sinfonias e dos Concertos":"Mendelssohn Series — Complete Symphonies and Concertos","Concerto Lounge":"Lounge Concert","Diz — Concerto":"Diz — Concert","Festa do Avante! 2026":"Avante! Festival 2026","Ganso — Ciclo Novas Quintas":"Ganso — New Thursdays Series","Guimarães Jazz — Toninho Horta Quarteto c/ Orquestra de Guimarães":"Guimarães Jazz — Toninho Horta Quartet with Guimarães Orchestra","Jazz no Centro Histórico — Dixie Gang":"Jazz in the Historic Centre — Dixie Gang","Juntos pela Música":"Together for Music","Kevin Morby com Ensemble da Escola Profissional de Música de Espinho":"Kevin Morby with the Espinho Professional Music School Ensemble","Noites de Orfeu — ciclo de música e mitologia":"Nights of Orpheus — Music and Mythology Series","Orquestra Jazz de Leiria + Christian McBride":"Leiria Jazz Orchestra + Christian McBride","Os Músicos do Tejo — Música Portuguesa dos séculos XVI e XVII":"Os Músicos do Tejo — Portuguese Music from the 16th and 17th Centuries","The Jazz Room — Tributo a Frank Sinatra e Louis Armstrong":"The Jazz Room — Tribute to Frank Sinatra and Louis Armstrong","TT — 20 anos de RNB: Come Closer":"TT — 20 Years of R&B: Come Closer","UHF — Podia Ser Natal":"UHF — It Could Be Christmas","Under The Doom Festival 2026 — X Edição":"Under The Doom Festival 2026 — 10th Edition","Em Casa D'Amália — O Concerto ao Vivo":"Em Casa D'Amália — The Live Concert","Concerto Solidário — UHF e The Cartel":"Benefit Concert — UHF and The Cartel","Concerto de Natal 2026 — Jovem Orquestra Portuguesa":"Christmas Concert 2026 — Portuguese Youth Orchestra","Nanook, o Esquimó — cine-concerto por Nuno Costa e Óscar Graça":"Nanook of the North — Film Concert by Nuno Costa and Óscar Graça",
    "Programação musical por dia ainda não publicada pela organização":"Daily music programme not yet published by the organiser","Programação por dia ainda não publicada pela organização":"Daily programme not yet published by the organiser","Concertos, encenações e mercado quinhentista — programa detalhado por dia ainda não publicado":"Concerts, performances and a 16th-century market — detailed daily programme not yet published","Consulta a programação atualizada na fonte do festival":"See the latest programme on the festival’s source","Consulta a programação atualizada na fonte oficial do festival":"See the latest programme on the festival’s official source","Consulta a programação atualizada na página do promotor":"See the latest programme on the promoter’s page","Cartaz oficial do dia — música, artes visuais, performances, talks e comida":"Official daily line-up — music, visual arts, performances, talks and food","Warm-up no recinto principal; concerto exclusivo na Capela Velha apenas para portadores do passe exclusivo":"Warm-up at the main venue; exclusive concert at Capela Velha for exclusive-pass holders only"
  }));
  const eventTitleReplacements = [
    [/\bFestival Internacional de Música Exploratória\b/gi,"International Exploratory Music Festival"],[/\bFestas Populares de Corroios\b/g,"Corroios Popular Festival"],[/\bFestas de Corroios\b/g,"Corroios Festival"],[/\bFestas do Mar\b/g,"Sea Festival"],[/\bAmadora em Festa\b/g,"Amadora Festival"],[/\bFestival do Moscatel do Douro\b/g,"Douro Muscat Festival"],[/\bFesta do Avante!/g,"Avante! Festival"],[/\bFesta de abertura\b/gi,"Opening Party"],[/\bXL Festival de Folclore\b/g,"XL Folk Festival"],[/\bVencedor do Concurso Talenta-te\b/g,"Winner of the Talenta-te Competition"],
    [/\bConcerto de Natal\b/g,"Christmas Concert"],[/\bClássicos de Natal\b/g,"Christmas Classics"],[/\bConcerto Solidário\b/g,"Benefit Concert"],[/\bCine Concerto\b/g,"Film Concert"],[/\bcine-concerto por\b/gi,"film concert by"],[/\bTributo aos?\b/gi,"Tribute to"],[/\bO melhor (?:de|dos?)\b/gi,"The Best of"],[/\bao vivo\b/gi,"live"],[/\bexperiência intimista\b/gi,"intimate experience"],[/\bsessões e horários\b/gi,"sessions and times"],[/\bprogramação do dia\b/gi,"daily programme"],[/\bprogramação\b/gi,"programme"],[/\bDJs após os concertos\b/gi,"DJs after the concerts"],[/\bCartaz anunciado:/gi,"Line-up announced:"],[/\bCartaz final:/gi,"Final line-up:"],[/\bDia para escolas\b/gi,"Schools day"],[/\bDia para famílias\b/gi,"Family day"],[/\b com \b/gi," with "],[/\b(\d+) anos\b/gi,"$1 Years"],[/\b(\d+)\.ª edição\b/gi,(_,number)=>`${number}${number === "1" ? "st" : number === "2" ? "nd" : number === "3" ? "rd" : "th"} Edition`],
    [/\bjaneiro\b/gi,"January"],[/\bfevereiro\b/gi,"February"],[/\bmarço\b/gi,"March"],[/\babril\b/gi,"April"],[/\bmaio\b/gi,"May"],[/\bjunho\b/gi,"June"],[/\bjulho\b/gi,"July"],[/\bagosto\b/gi,"August"],[/\bsetembro\b/gi,"September"],[/\boutubro\b/gi,"October"],[/\bnovembro\b/gi,"November"],[/\bdezembro\b/gi,"December"]
  ];

  function translateEventTitle(value) {
    if (language !== "en" || value == null) return value;
    const source = String(value);
    const trimmed = source.trim();
    if (!trimmed) return source;
    let result = eventTitleExact.get(trimmed) || trimmed;
    if (result === trimmed) for (const [pattern, replacement] of eventTitleReplacements) result = result.replace(pattern, replacement);
    return source.replace(trimmed, result);
  }

  function translateComposite(value) {
    if (!String(value).includes("·")) return value;
    return String(value).split(/(\s*·\s*)/).map(part => {
      const trimmed = part.trim();
      return !trimmed || trimmed === "·" ? part : part.replace(trimmed, exact.get(trimmed) || trimmed);
    }).join("");
  }

  const replacements = [
    [/^A seguir em (.+)$/,"Up next in $1"],[/^Página (\d+) de (\d+)$/,"Page $1 of $2"],[/^(\d+) eventos$/,"$1 events"],[/^1 evento$/,"1 event"],[/^(\d+) selecionados?$/,"$1 selected"],[/^\+(\d+) eventos$/,"+$1 events"],
    [/^Abrir (.+)$/,(_,title)=>`Open ${translateEventTitle(title)}`],[/^(.+) — Desvio$/,(_,title)=>`${translateEventTitle(title)} — Desvio`],
    [/^Concertos em Portugal$/,"Concerts in Portugal"],[/^Concertos este fim de semana$/,"Concerts this weekend"],[/^Concertos grátis$/,"Free concerts"],[/^Festivais em Portugal em (\d{4})$/,"Festivals in Portugal in $1"],[/^Concertos no distrito de (.+)$/,"Concerts in the $1 district"],[/^Concertos em (.+)$/,"Concerts in $1"],[/^(.+) ao vivo em (.+)$/,"Live $1 in $2"],[/^(.+) em Portugal$/,"$1 in Portugal"],
    [/^(\d+) concertos e eventos de música ao vivo para este fim de semana em Portugal, com datas, salas, cartazes e ligações oficiais\.$/,"$1 concerts and live-music events in Portugal this weekend, with dates, venues, posters and official links."],[/^(\d+) concertos e eventos de música com entrada livre em Portugal, confirmados em fontes oficiais\.$/,"$1 free concerts and music events in Portugal, confirmed through official sources."],[/^(\d+) eventos em agenda: (.+)\. Datas, salas, cartazes, bilhetes e fontes oficiais no Desvio\.$/,"$1 listed events: $2. Dates, venues, posters, tickets and official sources on Desvio."],
    [/^(\d{1,2}) de (janeiro|fevereiro|março|abril|maio|junho|julho|agosto|setembro|outubro|novembro|dezembro)(?: de (\d{4}))?$/i,(_,day,month,year)=>`${day} ${{janeiro:"January",fevereiro:"February",março:"March",abril:"April",maio:"May",junho:"June",julho:"July",agosto:"August",setembro:"September",outubro:"October",novembro:"November",dezembro:"December"}[month.toLowerCase()]}${year ? ` ${year}` : ""}`],
    [/^Cartaz oficial de (.+)$/,(_,title)=>`Official poster for ${translateEventTitle(title)}`],[/^Ampliar cartaz oficial de (.+)$/,(_,title)=>`Enlarge the official poster for ${translateEventTitle(title)}`],[/^Cartaz oficial ampliado de (.+)$/,(_,title)=>`Enlarged official poster for ${translateEventTitle(title)}`],
    [/^Copia este link: /,"Copy this link: "],[/^A mostrar os eventos mais próximos da região de (.+)\.$/,"Showing the events closest to $1."],[/^Ainda não encontrámos cartazes oficiais perto de (.+)\.$/,"We have not found official posters near $1 yet."],
    [/^Vais corrigir: (.+)\. Indica o que mudou e deixa uma fonte oficial que o confirme\.$/,"You are correcting: $1. Tell us what changed and provide an official source confirming it."],
    [/\bBilhete de fim de semana\b/gi,"Weekend ticket"],[/\bBilhete diário\b/gi,"Day ticket"],[/\bbilhetes diários\b/gi,"day tickets"],[/\bdiários\b/gi,"day tickets"],[/\bpasse (\d+) dias\b/gi,"$1-day pass"],[/\bpasse geral\b/gi,"full pass"],[/\bPasse e bilhetes\b/gi,"Pass and tickets"],[/\bfim de semana\b/gi,"weekend"],[/\bEntrada Permanente\b/g,"Full pass"],
    [/\bA partir das\b/gi,"From"],[/\bA partir dos (\d+) anos\b/gi,"Ages $1+"],[/\bAté às\b/gi,"Until"],[/(?<![\p{L}\p{N}])até(?![\p{L}\p{N}])/giu,"to"],[/\bDesde\b/g,"From"],[/\bdesde\b/g,"from"],[/\bpré-venda\b/gi,"advance"],[/\bà porta\b/gi,"at the door"],[/\bno dia\b/gi,"on the day"],[/\btaxas\b/gi,"fees"],[/\bsócios\b/gi,"members"],
    [/\bBilhetes disponíveis\b/gi,"Tickets available"],[/\bBilheteira oficial ainda não localizada\b/gi,"Official ticketing not found yet"],[/\bBilheteira por confirmar\b/gi,"Ticketing to be confirmed"],[/\bConsultar no site\b/gi,"See website"],[/\bConsultar bilheteira oficial\b/gi,"See official ticketing"],[/\bConsultar organização\b/gi,"Check with organiser"],[/\bConsultar programa\b/gi,"See programme"],[/\bConsultar horários\b/gi,"See times"],[/\bConsultar sessões\b/gi,"See sessions"],[/\bConsultar bilheteira\b/gi,"See ticketing"],
    [/\bPortas\b/gi,"Doors"],[/\bAbertura\b/gi,"Doors"],[/\binício\b/gi,"start"],[/\bHorários por palco no app\b/gi,"Stage times in the app"],[/\bHorário por palco a anunciar\b/gi,"Stage times to be announced"],[/\bHorário a anunciar\b/gi,"Time to be announced"],[/\bHorários por anunciar\b/gi,"Times to be announced"],[/\bHorário por anunciar\b/gi,"Time to be announced"],[/\bhorários\b/gi,"times"],[/\bhorário\b/gi,"time"],[/\bpor palco\b/gi,"by stage"],[/\ba anunciar\b/gi,"to be announced"],[/\ba confirmar\b/gi,"to be confirmed"],
    [/\bMenores de (\d+) acompanhados não pagam\b/gi,"Accompanied children under $1 enter free"],[/\bmenores acompanhados não pagam\b/gi,"accompanied children enter free"],[/\bMenores de (\d+) acompanhados\b/gi,"Under-$1s must be accompanied"],[/\b(\d+–\d+) acompanhados\b/gi,"Ages $1 must be accompanied"],[/\bentrada M\/(\d+)\b/gi,"admission ages $1+"],
    [/\bEntrada gratuita\b/gi,"Free admission"],[/\bEntrada livre\b/gi,"Free admission"],[/\bentrada limitada à lotação\b/gi,"admission subject to capacity"],[/\bEsgotado\b/gi,"Sold out"],[/\bDisponível\b/gi,"Available"],[/\bPor confirmar\b/gi,"To be confirmed"],[/\bCancelado\b/gi,"Cancelled"],[/\btemporariamente indisponíveis\b/gi,"temporarily unavailable"],[/\bnovas unidades anunciadas\b/gi,"additional tickets announced"],[/\bdisponibilidade\b/gi,"availability"],[/\breembolso\b/gi,"refund"],
    [/\bpágina oficial do evento\b/gi,"official event page"],[/\bpágina do evento\b/gi,"event page"],[/\bpágina oficial\b/gi,"official page"],[/\bprogramação oficial\b/gi,"official programme"],[/\bprogramação\b/gi,"programme"],[/\bprograma\b/gi,"programme"],[/\bfonte oficial\b/gi,"official source"],[/\binformação publicada\b/gi,"published information"],[/\borganização\b/gi,"organiser"],[/\bvários palcos\b/gi,"multiple stages"],[/\bvários espaços\b/gi,"multiple spaces"],[/\bdois palcos\b/gi,"two stages"],
    [/\bconsultar no bilheteiro\b/gi,"check with ticket seller"],[/\bconsultar\b/gi,"check"],[/\bconcertos\b/gi,"concerts"],[/\bconcerto\b/gi,"concert"],[/\bbilhetes\b/gi,"tickets"],[/\bbilheteira\b/gi,"ticketing"],[/\bbilhete solidário\b/gi,"charity ticket"],[/\bbilhete\b/gi,"ticket"],[/\bcartazes\b/gi,"posters"],[/\bcartaz\b/gi,"poster"],[/\boficiais\b/gi,"official"],[/\b(\d+)\.ª fase\b/gi,"phase $1"],
    [/\bjaneiro\b/gi,"January"],[/\bfevereiro\b/gi,"February"],[/\bmarço\b/gi,"March"],[/\babril\b/gi,"April"],[/\bmaio\b/gi,"May"],[/\bjunho\b/gi,"June"],[/\bjulho\b/gi,"July"],[/\bagosto\b/gi,"August"],[/\bsetembro\b/gi,"September"],[/\boutubro\b/gi,"October"],[/\bnovembro\b/gi,"November"],[/\bdezembro\b/gi,"December"]
  ];

  function translate(value) {
    if (language !== "en" || value == null) return value;
    const source = String(value);
    const trimmed = source.trim();
    if (!trimmed) return source;
    let result = exact.get(trimmed) || translateComposite(trimmed);
    for (const [pattern, replacement] of replacements) result = result.replace(pattern, replacement);
    return source.replace(trimmed, result);
  }

  function translateNode(node) {
    const titleContext = node.parentElement?.closest?.(".featured-copy h3,.event-title,.landing-event h2,.event-view h1,.similar-events strong,.festival-day-panel strong,.nearby-card h3,.calendar-day a,[data-i18n-event-title]");
    return titleContext ? translateEventTitle(node.nodeValue) : translate(node.nodeValue);
  }

  function translateElement(root) {
    if (language !== "en" || !root) return;
    const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT, { acceptNode: node => node.parentElement?.closest("script,style,noscript") ? NodeFilter.FILTER_REJECT : NodeFilter.FILTER_ACCEPT });
    const nodes = [];
    while (walker.nextNode()) nodes.push(walker.currentNode);
    nodes.forEach(node => { const next = translateNode(node); if (next !== node.nodeValue) node.nodeValue = next; });
    const elements = root.matches?.("*") ? [root, ...root.querySelectorAll("*")] : [...root.querySelectorAll?.("*") || []];
    for (const element of elements) for (const attribute of ["aria-label","alt","placeholder","title","content"]) {
      if (!element.hasAttribute?.(attribute)) continue;
      const current = element.getAttribute(attribute); const next = translate(current); if (next !== current) element.setAttribute(attribute, next);
    }
  }

  function setLanguage(next) {
    try { localStorage.setItem(storageKey, next); } catch { /* storage may be disabled */ }
    const url = new URL(location.href);
    if (next === "en") url.searchParams.set("lang", "en"); else url.searchParams.delete("lang");
    location.href = url.toString();
  }

  function initialise() {
    document.querySelectorAll("[data-lang-toggle]").forEach(button => {
      button.textContent = language === "en" ? "PT" : "EN";
      button.setAttribute("aria-label", language === "en" ? "Ver site em português" : "View site in English");
      button.addEventListener("click", () => setLanguage(language === "en" ? "pt" : "en"));
    });
    translateElement(document.documentElement);
    if (language === "en") new MutationObserver(mutations => {
      for (const mutation of mutations) {
        if (mutation.type === "characterData") { const next = translateNode(mutation.target); if (next !== mutation.target.nodeValue) mutation.target.nodeValue = next; }
        mutation.addedNodes.forEach(node => { if (node.nodeType === Node.TEXT_NODE) { const next = translateNode(node); if (next !== node.nodeValue) node.nodeValue = next; } else if (node.nodeType === Node.ELEMENT_NODE) translateElement(node); });
      }
    }).observe(document.body, { subtree:true, childList:true, characterData:true });
  }

  window.DESVIO_I18N = { language, locale, t: translate, eventTitle: translateEventTitle, setLanguage, apply: translateElement };
  if (document.readyState === "loading") document.addEventListener("DOMContentLoaded", initialise, { once:true }); else initialise();
})();
